load("@rules_cc//cc/toolchains:args.bzl", "cc_args")
load("@rules_cc//cc/toolchains/impl:documented_api.bzl", "cc_args_list")

package(default_visibility = ["//visibility:public"])

cc_args(
    name = "mingw_headers_include_search_paths",
    actions = [
        "@rules_cc//cc/toolchains/actions:compile_actions",
    ],
    args = [
        "-isystem",
        "{mingw_generated_headers_crt}",
        "-isystem",
        "{mingw_w64_crt_include}",
        "-isystem",
        "{mingw_w64_headers_include}",
        "-isystem",
        "{mingw_w64_headers_crt}",
        "-isystem",
        "{mingw_w64_crt_crt}",
    ],
    format = {
        "mingw_generated_headers_crt": "@mingw//:mingw_generated_headers_crt_directory",
        "mingw_w64_crt_include": "@mingw//:mingw_w64_crt_include_directory",
        "mingw_w64_headers_include": "@mingw//:mingw_w64_headers_include_directory",
        "mingw_w64_headers_crt": "@mingw//:mingw_w64_headers_crt_directory",
        "mingw_w64_crt_crt": "@mingw//:mingw_w64_crt_crt_directory",
    },
    allowlist_include_directories = [
        "@mingw//:mingw_generated_headers_crt_directory",
        "@mingw//:mingw_w64_crt_include_directory",
        "@mingw//:mingw_w64_headers_include_directory",
        "@mingw//:mingw_w64_headers_crt_directory",
        "@mingw//:mingw_w64_crt_crt_directory",
    ],
    data = [
        "@mingw//:mingw_headers",
    ],
)

cc_args(
    name = "mingw_library_search_paths_x86_64",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "-L{mingw_library_search_path}",
    ],
    format = {
        "mingw_library_search_path": "@mingw//:mingw_import_libraries_x86_64_directory",
    },
    allowlist_include_directories = [
        "@mingw//:mingw_import_libraries_x86_64_directory",
    ],
    data = [
        "@mingw//:mingw_import_libraries_x86_64",
    ],
)

cc_args(
    name = "mingw_library_search_paths_aarch64",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "-L{mingw_library_search_path}",
    ],
    format = {
        "mingw_library_search_path": "@mingw//:mingw_import_libraries_aarch64_directory",
    },
    allowlist_include_directories = [
        "@mingw//:mingw_import_libraries_aarch64_directory",
    ],
    data = [
        "@mingw//:mingw_import_libraries_aarch64",
    ],
)

cc_args_list(
    name = "windows_library_search_args",
    args = select({
        "@platforms//cpu:x86_64": [
            ":mingw_library_search_paths_x86_64",
        ],
        "@platforms//cpu:aarch64": [
            ":mingw_library_search_paths_aarch64",
        ],
        "//conditions:default": [],
    }),
)

cc_args(
    name = "mingw_default_libs_x86_64",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "{kernel32_onecore_import_lib}",
    ],
    format = {
        "kernel32_onecore_import_lib": "//runtimes/mingw:kernel32_onecore_import_lib_x86_64",
    },
    data = [
        "//runtimes/mingw:kernel32_onecore_import_lib_x86_64",
    ],
)

cc_args(
    name = "mingw_default_libs_aarch64",
    actions = [
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
    args = [
        "{kernel32_onecore_import_lib}",
    ],
    format = {
        "kernel32_onecore_import_lib": "//runtimes/mingw:kernel32_onecore_import_lib_aarch64",
    },
    data = [
        "//runtimes/mingw:kernel32_onecore_import_lib_aarch64",
    ],
)

cc_args_list(
    name = "windows_default_libs",
    args = select({
        "@platforms//cpu:x86_64": [
            ":mingw_default_libs_x86_64",
        ],
        "@platforms//cpu:aarch64": [
            ":mingw_default_libs_aarch64",
        ],
        "//conditions:default": [],
    }),
)
